// clients/Angular/src/app/components/user-form/user-form.component.ts
import { Component } from '@angular/core';
import { UserService } from '../../services/user.service';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-user-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './user-form.component.html',
  styleUrl: './user-form.component.css'
})
export class UserFormComponent {
  user: any = {
    name: '',
    email: '',
    age: '',
    adress: '',
    password: ''
  };
  userId: string | null = null;

  constructor(private userService: UserService, private route: ActivatedRoute, private router: Router) {}

  ngOnInit(): void {
    this.userId = this.route.snapshot.paramMap.get('id');
    if (this.userId) {
      this.userService.getUserById(this.userId).subscribe((data) => {
        this.user = data;
        console.log(this.user);
      });
    }
  }

  onSubmit() {
    if (this.userId) {
      this.userService.updateUser(this.userId, this.user).subscribe(() => {
        this.router.navigate(['/users']);
      });
    } else {
      this.userService.createUser(this.user).subscribe(() => {
        this.router.navigate(['/users']);
      });
    }
  }
}

<div class="container mt-4">
    <h2>{{ userId ? 'Edit' : 'Add' }} User</h2>
    <form (ngSubmit)="onSubmit()" #userForm="ngForm">
      <!-- Name Field -->
      <div class="mb-3">
        <label>Name</label>
        <input 
          [(ngModel)]="user.name" 
          name="name" 
          class="form-control" 
          required 
          #name="ngModel">
        <div *ngIf="name.invalid && (name.dirty || name.touched)" class="text-danger">
          Please fill the name input.
        </div>
      </div>
  
      <!-- Email Field -->
      <div class="mb-3">
        <label>Email</label>
        <input 
          [(ngModel)]="user.email" 
          name="email" 
          type="email" 
          class="form-control" 
          required 
          #email="ngModel">
        <div *ngIf="email.invalid && (email.dirty || email.touched)" class="text-danger">
          Please fill the email input.
        </div>
      </div>
  
      <!-- Age Field -->
      <div class="mb-3">
        <label>Age</label>
        <input 
          [(ngModel)]="user.age" 
          name="age" 
          type="number" 
          class="form-control" 
          required 
          #age="ngModel">
        <div *ngIf="age.invalid && (age.dirty || age.touched)" class="text-danger">
          Please fill the age input.
        </div>
      </div>
  
      <!-- Address Field -->
      <div class="mb-3">
        <label>Address</label>
        <input 
          [(ngModel)]="user.address" 
          name="address" 
          class="form-control" 
          required 
          #address="ngModel">
        <div *ngIf="address.invalid && (address.dirty || address.touched)" class="text-danger">
          Please fill the address input.
        </div>
      </div>
  
      <!-- Password Field -->
      <div class="mb-3">
        <label>Password</label>
        <input 
          [(ngModel)]="user.password" 
          name="password" 
          type="password" 
          class="form-control" 
          required 
          #password="ngModel">
        <div *ngIf="password.invalid && (password.dirty || password.touched)" class="text-danger">
          Please fill the password input.
        </div>
      </div>
  
      <!-- Submit Button -->
      <button 
        class="btn btn-primary" 
        [disabled]="userForm.invalid">
        {{ userId ? 'Update' : 'Create' }}
      </button>
    </form>
  </div>

// clients/React/src/components/UserForm.jsx
import React, { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { createUser, getUser, updateUser } from "../redux/userSlice";
import { useParams, useNavigate } from "react-router-dom";

export default function UserForm() {
  const [form, setForm] = useState({
    name: "",
    email: "",
    age: "",
    adress: "",
    password: "",
  });

  const { id } = useParams();
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const user = useSelector((state) =>
    state.users.list.find((user) => user._id === id)
  );

  useEffect(() => {
    if (id && !user) {
      dispatch(getUser(id)).then((res) => {
        if (res.payload) {
          setForm(res.payload);
        }
      });
    } else if (user) {
      setForm(user);
    }
  }, [id, user, dispatch]);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (id) {
      dispatch(updateUser({ id, data: form }));
    } else {
      dispatch(createUser(form));
    }
    navigate("/");
  };

  return (
    <div className="container mt-4">
      <h2>{id ? "Edit" : "Add"} User</h2>
      <form onSubmit={handleSubmit}>
        {["name", "email", "age", "adress", "password"].map((field) => (
          <div className="mb-3" key={field}>
            <label className="form-label text-capitalize">{field}</label>
            <input
              type={
                field === "password"
                  ? "password"
                  : field === "age"
                  ? "number"
                  : "text"
              }
              name={field}
              className="form-control"
              value={form[field]}
              onChange={handleChange}
              required
            />
          </div>
        ))}
        <button className="btn btn-primary">{id ? "Update" : "Create"}</button>
      </form>
    </div>
  );
}
